title: IPC2023 Planning and RL Track
description: 2023 International Planning Competition
theme: jekyll-theme-leap-day
show_downloads: false
github:
  is_project_page: false
# Google Analytics
#google_analytics: G-7H664P9SY1
google_analytics: UA-247039268-1
